singularity_image: /project/lbarreiro/USERS/daniel/SOFTWARE/run_saigeqtl.sh
celltype: NK_NI
gene_list: /project/lbarreiro/USERS/daniel/asthma_project/QTLmapping/Saige/step1/inputs/NK_NI_gene_list.txt
pheno_file: /project/lbarreiro/USERS/daniel/asthma_project/QTLmapping/Saige/step1/inputs/NK_NI_counts.w.covs.txt
plink_prefix: /project/lbarreiro/USERS/daniel/asthma_project/QTLmapping/Saige/step1/inputs/Haley_0.2maf_random1k